version: "3.8"
services:
  tweb.dependencies:
    container_name: tweb.dependencies
    build:
      context: .
      dockerfile: .docker/Dockerfile_dependencies
    volumes:
      - node_modules:/app/node_modules
    command: pnpm install --frozen-lockfile

  tweb.develop:
    container_name: tweb.develop
    build:
      context: .
      dockerfile: .docker/Dockerfile_develop
    volumes:
      - "./:/app"
      - node_modules:/app/node_modules
    ports:
      - 8080:8080
    environment:
      - VITEST=1
      - USE_OWN_SOLID=true
    command: pnpm start-in-docker

  tweb.production:
    container_name: tweb.production
    build:
      context: .
      dockerfile: .docker/Dockerfile_production
    ports:
      - 80:80

volumes:
  node_modules:
